### ISSUE TITLE
Inserting new items

### ISSUE THREAD

**Issue by AyushSahu77** [AniqJaved/bakeryshop#2]
Firstly, I am not able to insert new product on to the sqlite database by using the below command it shows syntax error and i can't debug that window,
```sh
INSERT INTO product (id, title, thumbnail, description)
VALUES (‘abc123’, ‘Headphones’, ‘https://bit.ly/3MyfSqe’, ‘Bowers & Wilkins (B&W) PX7 Over-ear Noise Cancelling Wireless Headphones’);
```

**Comment by AniqJaved** [comment]
Kindly create separate issue for all the queries mentioned above. And also change name of this issue.I will try to answer the first query in this issue.

**Comment by AniqJaved** [comment]
You need to update the columns instead of adding new ones.

Firstly use command
SELECT * from product

This will give you all the columns of the product field. You need to copy the id of product.
Then use
UPDATE product
SET title='red frost cake', thumbnail='https://www.google.com', description='Cake with frosty icing'
WHERE id='xyz';

**Comment by AyushSahu77** [comment]
I managed to add new items, but thanks anyway

Actually the issue was indeed with the syntax, I wasn't aware of some quotes and inverted commas
